version: "3"
services:
  must-pv1800-lifepo4:
    image: must-pv1800-lifepo4
    hostname: must-pv1800-lifepo4
    container_name: must-pv1800-lifepo4
    restart: always
    environment:
      MUST_Config__Cron: "0/2 * * * * ?"
      MUST_Config__IsTest: false
      MUST_Config__PortName: "/dev/ttyUSB0"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
    # privileged: true